/**
 * Spoken welcome cues for the language switch.
 *
 * Toggling to Swahili plays "Karibu ATZ Company Limited"; toggling to English
 * plays "Welcome ATZ Company Limited". The files are not generated by the
 * build — drop the recorded MP3s into `public/audio/` (see the README there).
 *
 * The EN and SW trees are separate root layouts, so switching language is a
 * full document navigation. `playLangCue` therefore resolves when the clip
 * has finished (or failed, or overrun `MAX_WAIT_MS`), and the caller
 * navigates *after* that — otherwise the new page would cut the voice off.
 */
import type { Lang } from "./locales";

export const LANG_AUDIO: Record<Lang, string> = {
  en: "/audio/welcome.mp3",
  sw: "/audio/karibu.mp3",
};

/** Upper bound on how long the switch waits for the clip. */
const MAX_WAIT_MS = 3000;

/**
 * Plays the cue for `lang`. Resolves on `ended`, on any error (file missing,
 * autoplay refused) or after `MAX_WAIT_MS`, whichever comes first — it never
 * rejects, so the language switch always completes.
 */
export function playLangCue(lang: Lang): Promise<void> {
  return new Promise((resolve) => {
    let settled = false;
    const done = () => {
      if (settled) return;
      settled = true;
      window.clearTimeout(timer);
      resolve();
    };
    const timer = window.setTimeout(done, MAX_WAIT_MS);

    let audio: HTMLAudioElement;
    try {
      audio = new Audio(LANG_AUDIO[lang]);
    } catch {
      done();
      return;
    }
    audio.preload = "auto";
    audio.addEventListener("ended", done, { once: true });
    audio.addEventListener(
      "error",
      () => {
        remindAboutAudioFiles(lang);
        done();
      },
      { once: true }
    );
    // `play()` rejects when the browser blocks it (no gesture, muted tab) or
    // the source is unusable — either way, switch language without the cue.
    audio.play().catch(() => done());
  });
}

let reminded = false;

/**
 * Development reminder that the voice clips are missing. Logged once per
 * page: the toggle renders twice (desktop + mobile bars), and nagging on
 * every click helps nobody.
 */
function remindAboutAudioFiles(lang: Lang) {
  if (reminded || process.env.NODE_ENV === "production") return;
  reminded = true;
  console.info(
    "%c[lang-audio] Voice cue not found: " + LANG_AUDIO[lang],
    "color:#c9a84c;font-weight:bold",
    "\nDrop the generated deep-male-voice MP3s into public/audio/:",
    "\n  public/audio/karibu.mp3  — “KARIBU ATZ COMPANY LIMITED”",
    "\n  public/audio/welcome.mp3 — “WELCOME ATZ COMPANY LIMITED”",
    "\nUntil then the language switch works silently."
  );
}

/**
 * Dev-only startup check: HEAD both clips once and log the reminder if either
 * is missing, so the gap is visible before anyone clicks the toggle.
 */
export function checkLangAudioAvailable() {
  if (reminded || process.env.NODE_ENV === "production") return;
  const langs = Object.keys(LANG_AUDIO) as Lang[];
  Promise.all(
    langs.map((lang) =>
      fetch(LANG_AUDIO[lang], { method: "HEAD" })
        .then((r) => {
          // Next's dev server answers a missing public file with its 404
          // page, so check the content type as well as the status.
          const type = r.headers.get("content-type") ?? "";
          return r.ok && type.startsWith("audio/");
        })
        .catch(() => false)
    )
  ).then((present) => {
    const missing = langs.find((_, i) => !present[i]);
    if (missing) remindAboutAudioFiles(missing);
  });
}
